### ISSUE TITLE
Prevent Win11 from installing Teams

### ISSUE THREAD

**Issue by StenApp** [ianis58/tiny11builder#11]
Hi,

i read an article about Teams, which is not part of the iso. It get‘s installed after the setup…
https://woshub.com/remove-teams-chat-windows/#:~:text=REG_DWORD%20%2Fd%203-,How%20to%20Completely%20Uninstall%20Teams%20in%20Windows%2011%3F,clicking%20Uninstall%20in%20the%20menu).

**Comment by StenApp** [comment]
It is noteworthy that Teams Chat is not built-in into the Windows 11 install image. This APPX is downloaded and installed automatically after the Windows setup is complete. Therefore, you will not be able to remove it from the Windows installation image (install.wim) using [this method](https://woshub.com/remove-built-apps-features-editions-install-wim-image/).

Currently, the only way to prevent automatic Teams Chat installation is to enable the ConfigureChatAutoInstall registry parameter during Windows setup.

You can create the AutoUnattend.xml file and copy it to the root of the Windows 11 installation image/flash drive (like it is described in the article [How to Install Windows 11 Without TPM and Secure Boot Checks](https://woshub.com/windows-11-unsupported-hardware-no-tpm-secure-boot/)). Here is a part of the AutoUnattend file to prevent Teams Chat installation:
```

<RunSynchronousCommand wcm:action="add">
<Order>1</Order>
<Path>reg add HKLM\Software\Microsoft\Windows\CurrentVersion\Communications /v ConfigureChatAutoInstall /t REG_DWORD /d 0 /f</Path>
</RunSynchronousCommand>
```

**Comment by ianis58** [comment]
Teams is indeed included in the Windows 11 installer.
That's why it is removed by the tiny11builder script, but you are right to say that it will just not work. It's installed back after some updates on a fresh install.
Also there is already an autounattend.xml file in this repo, and it tries to disable the Teams auto install.
There is also a registry tweak to disable that same feature.
None of this is working.
Or to be exact, it works, so if you start a newly installed windows 11, not connecting it to the internet, you will not have Teams. But if you connect to the internet and run some windows updates, it will be back.

**Comment by StenApp** [comment]
Can you try to add the reg thing they posted on the site and have a test?

**Comment by ianis-c** [comment]
It has the same effect in the registry. Only it's done differently: with a command line at first startup.
There is another way to toggle that setting using the autounattend.xml file that you can see there: https://github.com/ianis58/tiny11builder/blob/87955f820dafd3eb2c56a3bd88050d3a6a2ddfde/tools/autounattend.xml#LL11C16-L11C16

From what i've experienced, it's not a matter of successfully removing Teams, because we manage to achieve this.
The problematic subject is that after uninstalling it, Microsoft just force-push it to be installed back using Windows Update.

So whatever method we use to uninstall it, it will work, but temporarly.
