### ISSUE TITLE
Source Oscdimg binary directly from Microsoft

### ISSUE THREAD

**Issue by PolicyPuma4** [ianis58/tiny11builder#3]
As mentioned here https://github.com/ntdevlabs/tiny11builder/pull/43#issuecomment-1501074660, you can automate the download of just the Oscdimg binary directly from Microsoft. Downloading binaries from unofficial sources is generally a bad security practice. Having the script download the binary directly from Microsoft as a first step would increase user trust.

While not the reason for this issue, giving an option and instructions to manually source a Windows 11 disk image file directly from Microsoft would also be preferable.

**Comment by ianis58** [comment]
Thanks for your feedback and indeed I agree with your point of view.
I'm thinking of just removing the use of this binary, because in the first place it doesn't even seems really needed (iirc I've read someone explaining we can do the same work with some PowerShell commands).

**Comment by dragetd** [comment]
@ianis58 Do you have any reference about creating the ISO with only PowerShell? The only solutions I could find: Creating the ISO file structure manually which tedious and error-prone. Or using another Open Source project called DiscUtils which would still include a dll (binary) in this project.

Since downloading oscdimg.exe involves multiple files and an MSI run, downloading a single DLL might be a cleaner solution. But then again I did not find any download (not a powershell expert on how to actually use dependencies).

So in the End, downloading oscdimg.exe might be still the cleaner solution.

I am trying to collect the different improvements people have posted to the original project and throw them all into one new project, which is initially based on your form: https://github.com/dragetd/tiny11builder

I'd like to rename the project (to make it easier to find), document things well, include checksums and more PRs and suggestions from others while keeping it simple and clean. More than happy to chat or re-combine everything into your repo (or a new github organisation) to create 'the final solution' to this. :D

**Comment by Eiqnepm** [comment]
> Since downloading oscdimg.exe involves multiple files and an MSI run, downloading a single DLL might be a cleaner solution.

It does involve downloading multiple files, however their combined size only equates to 727 KiB, this is because the Oscdimg MSI is only responsible for creating the Oscdimg binaries while Windows ADK is being installed as a whole. Considering all the other automation this script involves, I can't see why downloading a single DLL would be any simpler than downloading the Oscdimg MSI directly from Microsoft and then extracting it.

**Comment by ianis58** [comment]
In fact, in the way I use the iso once it's build, i don't even need to create an iso at any point:
When I get my iso in the end, I just create a bootable USB flashdrive with it.
As I have an uefi on my motherboard, and not a legacy bios, I can only extract the iso as-is in an empty fat32 or ntfs USB flashdrive, and my system will allow me to boot from that.

Nowadays every PC have an uefi, and except if you have specific hardware or usage, I think you should always prefer using UEFI which allows to use GPT partition table (as opposed to legacy bios boot, which will install windows with an MBR partition table).

So what do you guys think: we could just go one step further and directly create a uefi bootable USB flashdrive, without even creating an iso?
Just have to detect USB drives, check capacity, maybe draw a little list in the PowerShell so the user can choose his drive letter.
