### ISSUE TITLE
Use existing windows 11 iso instead of download new one

### ISSUE THREAD

**Issue by zombozo12** [ianis58/tiny11builder#6]
how?

**Comment by ianis58** [comment]
Yes you can do that, you just have to comment out the lines that launch WindowsIsoDownloader in the PowerShell script.
Also you need to place your iso named windows11.iso in C:\windows11.iso

**Comment by vdub12** [comment]
I've tried that and it still errors. Seems like WindowsIsoDownloader isn't working making the script not work.

**Comment by ianis58** [comment]
@vdub12 can you provide screenshot or copy paste the logs?
Normally it's pretty verbose

**Comment by vdub12** [comment]
Unfortunately, I can't at the moment. However, the issue I had was the downloader wouldn't download the ISO file. I tried the downloader by itself and it still didn't work. It would just timeout.

**Comment by KcTec90** [comment]
@ianis58 I'm getting errors because C:\tiny11 doesn't exist. ($rootWorkdir)

**Comment by KcTec90** [comment]
I found a solution! Using my fork, you can replace the tiny11creator.ps1 file with mine and it seems to work :)
![image3t2023Japanesebeetle1583times847PARK](https://user-images.githubusercontent.com/74018250/236653592-495da74b-4587-4b1b-a8fa-0f713bb6b6fd.png)

**Comment by ianis58** [comment]
@StenApp 
You can try to go there: https://www.microsoft.com/software-download/windows11

Then under "Download Windows 11 Disk Image (ISO) for x64 devices", select the only option in the dropdown and click Download now.
Now under "Select the product language", right click the dropdown to inspect it, and look how are formed the values. You should be able to replace it in the WindowsIsoDownloader config.json file :)
But it might cause issues with the rest of the script I don't know as it's untested.

An easier solution is just to install the OS in English, then in the settings you can just add a new language by installing it (it downloads it from Microsoft automatically).
I do this on my installs, because I never use English as my display language in windows. It works like a charm.

**Comment by StenApp** [comment]
Is there a possibility to add a question whether to use your downloader or use a specifyable iso file?
